#!/usr/bin/env bash
#This script displays numbers 1-100 with requirements
for ((i=1;i<=100;i++))
do 
        if (( num % 3 == 0 && num % 5 == 0 ))
        then
                echo "FizzBuzz"
        elif (( num % 3 == 0 ))
        then
                echo "Fizz"
        elif (( num % 5 == 0 ))
        then
                echo "Buzz"
        else
                echo "$num"
        fi
done
