#!/usr/bin/env bash
#A scipt that displays the content of the file /etc/passwd display specific requirements
Filename="/etc/passwd"
while IFS=: read -r username userid homedir
do
	echo "$username, $userid, $homedir"
done < $Filename
