#!/usr/bin/env bash
#Write a sctipt that displays the content of the file /etc/passwd, using the while loop + IFS

while IFS=':' read -r username _ userid _ GID _ homedir _ shell 
do	
	echo "The user $username is part of the $GID gang, lives in $homedir and rides $shell."
	echo "$userid/'s place is protected by the passcode PASSWORDd, more info about the user here: $USER ID INFO
done < /etc/passwd
