#!/usr/bin/env bash
#creates the file /var/run/myscript.pid containing its PID 
	echo $$ > /var/run/myscript.pid
	trap " echo 'I hate the kill command'; rm /var/run/myscript.pid; exit " 15
	trap " echo 'Y U no love me?!' " 2
	trap " rm /var/run/myscript.pid; exit " 3
while :
do
	echo " To infinity and beyond "
	sleep 2
done
