#!/usr/bin/env bash
#manage my process
        if [ "$1" == "start" ]
        then
                ./manage_my_process &
                echo "$!" > /var/run/my_process.pid
                echo "manage_my_process started"
        elif [ "$1" == "stop" ]
        then
                kill "$( cat /var/run/my_process.pid )"
                sudo rm /var/run/my_process.pid
                echo "manage_my_process stopped"
        elif [ "$1" == "restart" ]
        then
                kill "$( cat /var/run/my_process.pid )"
                sudo rm /var/run/my_process.pid
                ./manage_my_process &
                echo "$!" > /var/run/my_process.pid
                echo "manage_my_process restarted"

        else
                echo "Usuage: manage_my_process {start|stop|restart}"
        fi

